on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template for Storage
    # - name: Run ARM deploy for Storage
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ secrets.AZURE_RG }}
    #     template: ./Storage/template-storage.json
    #     parameters: ./Storage/parameters-storage.json
      
      # Deploy ARM template for KeyVault
    # - name: Run ARM deploy for KeyVault
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ secrets.AZURE_RG }}
    #     template: ./KeyVault/azuredeploy-keyvault.json
    #     parameters: ./KeyVault/parameters-keyvault.json

      # Deploy ARM template for Synapse
    - name: Run ARM deploy for Synapse
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Synapse/Workspace/template-workspace.json
        parameters: ./Synapse/Workspace/parameters-workspace.json

      # Deploy Artifacts Synapse Workspace 
    - name: Deploy artifacts for Synapse Workspace
      uses: Azure/synapse-workspace-deployment
      with:
        TargetWorkspaceName: 'synapse-test-actions'
        TemplateFile: './Synapse/Artifact/template-artifact.json'
        ParametersFile: './Synapse/Artifact/parameters-artifact.json'
        environment: 'Azure Public'
        resourceGroup: ${{ secrets.AZURE_RG }}
        clientId: ${{ secrets.AZURE_CLIENTID }}
        clientSecret: ${{ secrets.AZURE_CLIENTSECRET }}
        subscriptionId: ${{ secrets.AZURE_SUBID }}
        tenantId: ${{ secrets.AZURE_TENANTID }}
        activeDirectoryEndpointUrl: ${{ secrets.AZURE_ADE }}
        resourceManagerEndpointUrl: ${{ secrets.AZURE_RME }}