on: [push]

name: Azure ARM
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupLocation: "eastus"
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Download artifact from the build stage instead of checking out code
    - name: Download arm-playground artifact from build
      uses: actions/download-artifact@v2
      with:
        name: arm-playground

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Ensures the Azure Resource Group exists before ARM deployment
    - uses: azure/cli@v1
      with:
        inlineScript: |
          #!/bin/bash
          if $(az group exists --name weekly-share) ; then
            echo "Azure resource group already exists, skipping creation..."
          else
            az group create --name weekly-share --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"
          fi

      # Deploy ARM template for KeyVault
    - name: Run ARM deploy for KeyVault
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: weekly-share
        template: ./KeyVault/Template.json
        parameters: ./KeyVault/Parameters.json

      # Deploy ARM template for Storage
    - name: Run ARM deploy for Storage
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: weekly-share
        template: ./Storage/Template.json
        parameters: ./Storage/Parameters.json
      
      # Deploy ARM template for Synapse
    - name: Run ARM deploy for Synapse
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: weekly-share
        template: ./Synapse/Workspace/Template.json
        parameters: ./Synapse/Workspace/Parameters.json

