on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template for Storage
    - name: Run ARM deploy for Storage
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Storage/azuredeploy-storage.json
        parameters: ./Storage/parameters-storage.json
      
      # Deploy ARM template for KeyVault
    - name: Run ARM deploy for KeyVault
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./KeyVault/azuredeploy-keyvault.json
        parameters: ./KeyVault/parameters-keyvault.json
      env:
        tenantId: ${{ secrets.AZURE_TENANTID }}
        objectIdJk:  ${{ secrets.AZURE_OBJECTID_JK }}
